import { Roboto } from 'next/font/google';
import { Bruno_Ace_SC } from 'next/font/google';

import "./globals.css";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto',
  display: 'swap',
});

const brunoAce = Bruno_Ace_SC({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-bruno',
  display: 'swap',
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${brunoAce.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
